// opdracht1/app/components/add/author.tsx
import React, { useState } from "react";

const AddAuthor: React.FC = () => {
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [birthYear, setBirthYear] = useState<number | "">("");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const newAuthor = { firstName, lastName, birthYear: Number(birthYear) };
    try {
      const response = await fetch("/api/create/author", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(newAuthor),
      });
      // Reload the page to see the new author
      if (response.ok) {
        window.location.reload();
      }
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <div>
        <label htmlFor="firstName">First Name:</label>
        <input
          type="text"
          id="firstName"
          value={firstName}
          onChange={(e) => setFirstName(e.target.value)}
          required
        />
      </div>
      <div>
        <label htmlFor="lastName">Last Name:</label>
        <input
          type="text"
          id="lastName"
          value={lastName}
          onChange={(e) => setLastName(e.target.value)}
          required
        />
      </div>
      <div>
        <label htmlFor="birthYear">Birth Year:</label>
        <input
          type="number"
          id="birthYear"
          value={birthYear}
          onChange={(e) =>
            setBirthYear(e.target.value ? Number(e.target.value) : "")
          }
          required
        />
      </div>
      <button type="submit">Add Author</button>
    </form>
  );
};

export default AddAuthor;

// opdracht2/src/components/details/author.vue
<template>
    <ion-content class="ion-padding">
        <ion-list>
            <ion-item v-for="(field, index) in fields" :key="index">
                <ion-label position="stacked">{{ field.label }}</ion-label>
                <ion-input v-model="selectedAuthor[field.model]"></ion-input>
            </ion-item>
        </ion-list>
        <ion-button @click="saveAuthor">Save</ion-button>
        <ion-button @click="closeModal">Close</ion-button>
    </ion-content>
</template>

<script setup lang="ts">
import { ref, defineProps, watch, defineEmits } from "vue";
import { IonButton, IonInput, IonContent, IonLabel, IonItem, IonList } from "@ionic/vue";
import axios from "axios";

// Define props
const props = defineProps<{
    author: Author;
}>();

// Define emits
const emit = defineEmits<{
    (e: 'close'): void;
}>();

// Initialize selectedAuthor
const selectedAuthor = ref<Author>({
    id: 0,
    firstName: '',
    lastName: '',
    birthYear: 0
});

// Define fields for the form
const fields: { label: string, model: keyof Author }[] = [
    { label: 'First Name', model: 'firstName' },
    { label: 'Last Name', model: 'lastName' },
    { label: 'Birth Year', model: 'birthYear' }
];

// Save author function
const saveAuthor = async () => {
    if (selectedAuthor.value.id === 0) {
        // Add new author
        await axios.post("https://wm.ziasserver.com/api/create/author", {
            firstName: selectedAuthor.value.firstName,
            lastName: selectedAuthor.value.lastName,
            birthYear: Number(selectedAuthor.value.birthYear)
        },
            { headers: { 'Content-Type': 'application/json' } }
        );
    } else {
        // Edit existing author
        await axios.post("https://wm.ziasserver.com/api/edit/author", {
            id: Number(selectedAuthor.value.id),
            firstName: selectedAuthor.value.firstName,
            lastName: selectedAuthor.value.lastName,
            birthYear: Number(selectedAuthor.value.birthYear)
        },
            { headers: { 'Content-Type': 'application/json' } }
        );
    };
    emit('close'); // Emit close event to parent component
};

// Close modal function
const closeModal = () => {
    emit('close'); // Emit close event to parent component
};

// Watch for props update to reflect in selectedAuthor
watch(() => props.author, (newAuthor) => {
    selectedAuthor.value = { ...newAuthor };
}, { immediate: true });

// Define Author interface
interface Author {
    id: number;
    firstName: string;
    lastName: string;
    birthYear: number;
}
</script>
