// opdracht2/src/components/details/book.vue
<template>
    <ion-content class="ion-padding">
        <ion-item v-for=" (field, index) in fields" :key="index">
            <ion-label position="stacked">{{ field.label }}</ion-label>
            <!--Title and ISBN textbox-->
            <ion-input v-if="field.model !== 'authorId' && field.model !== 'genreId'"
                v-model="selectedBook[field.model]"></ion-input>
            <!--Author and genre picker-->
            <ion-picker v-if="field.model === 'authorId' || field.model === 'genreId'"
                :columns="field.model === 'authorId' ? authors : genres" @ionChange="pickerChange">
                <ion-picker-column v-if="field.model === 'authorId'" :value="selectedBook.authorId" id="author">
                    <ion-picker-column-option v-for="author in authors" :value="author.id">
                        {{ author.firstName }} {{ author.lastName }}
                    </ion-picker-column-option>
                </ion-picker-column>
                <ion-picker-column v-if="field.model === 'genreId'" :value="selectedBook.genreId" id="genre">
                    <ion-picker-column-option v-for="genre in genres" :value="genre.id">
                        {{ genre.name }}
                    </ion-picker-column-option>
                </ion-picker-column>
            </ion-picker>
        </ion-item>
        <ion-button @click="saveBook">Save</ion-button>
        <ion-button @click="closeModal">Close</ion-button>
    </ion-content>
</template>

<script setup lang="ts">
import { ref, defineProps, watch, defineEmits, onMounted } from "vue";
import { IonButton, IonInput, IonContent, IonLabel, IonItem, IonPicker, IonPickerColumn, IonPickerColumnOption } from "@ionic/vue";
import axios from "axios";

// Define interfaces
interface Book {
    id: number;
    title: string;
    code: string;
    authorId: number;
    genreId: number;
}
interface Author {
    id: number;
    firstName: string;
    lastName: string;
    birthYear: number;
    popup?: boolean;
}
interface Genre {
    id: number;
    name: string;
    popup?: boolean;
}

const authors = ref<Author[]>([]);
const genres = ref<Genre[]>([]);

const fetchAuthors = async () => {
    try {
        const response = await axios.get(
            "https://wm.ziasserver.com/api/list/authors"
        );
        authors.value = response.data as Author[];
    } catch (error) {
        console.error("Error fetching authors:", error);
    }
};
const fetchGenres = async () => {
    try {
        const response = await axios.get(
            "https://wm.ziasserver.com/api/list/genres"
        );
        genres.value = response.data as Genre[];
    } catch (error) {
        console.error("Error fetching genres:", error);
    }
};

// Fetch authors and genres on component mount
onMounted(() => {
    fetchAuthors();
    fetchGenres();
});

const pickerChange = (e: CustomEvent) => {
    // Get selected value and column and update selectedBook
    const value = e.detail.value;
    const column = (e.target as HTMLElement).id;

    if (column === 'author') {
        selectedBook.value.authorId = value;
    } else if (column === 'genre') {
        selectedBook.value.genreId = value;
    }
};

// Define props
const props = defineProps<{
    book: Book;
}>();

// Define emits
const emit = defineEmits<{
    (e: 'close'): void;
}>();

// Initialize selectedBook
const selectedBook = ref<Book>({
    id: 0,
    title: '',
    code: '',
    authorId: 0,
    genreId: 0
});

// Define fields for the form
const fields: { label: string, model: keyof Book }[] = [
    { label: 'Title', model: 'title' },
    { label: 'ISBN', model: 'code' },
    { label: 'Author ID', model: 'authorId' },
    { label: 'Genre ID', model: 'genreId' }
];

// Save book function
const saveBook = async () => {
    if (selectedBook.value.id === 0) {
        // Add new book
        await axios.post("https://wm.ziasserver.com/api/create/book", {
            title: selectedBook.value.title,
            code: selectedBook.value.code,
            author: selectedBook.value.authorId,
            genre: selectedBook.value.genreId
        },
            { headers: { 'Content-Type': 'application/json' } }
        );
    } else {
        // Edit existing book
        await axios.post("https://wm.ziasserver.com/api/edit/book", {
            id: selectedBook.value.id,
            title: selectedBook.value.title,
            code: selectedBook.value.code,
            authorId: selectedBook.value.authorId,
            genreId: selectedBook.value.genreId
        },
            { headers: { 'Content-Type': 'application/json' } }
        );
    }
    emit('close'); // Emit close event to parent component
};

// Close modal function
const closeModal = () => {
    emit('close'); // Emit close event to parent component
};

// Watch for props update to reflect in selectedBook
watch(() => props.book, (newBook) => {
    selectedBook.value = { ...newBook };
}, { immediate: true });
</script>

// opdracht1/app/components/details/book.tsx
import React from "react";
import { useState, useEffect } from "react";

interface Book {
  id: number;
  title: string;
  code: string;
  authorId: number;
  genreId: number;
}
interface Author {
  id: number;
  firstName: string;
  lastName: number;
  birthYear: number;
}

interface Genre {
  id: number;
  name: string;
}

const BookPopUp: React.FC<{ book: Book }> = ({ book }) => {
  const [title, setTitle] = useState<string>(book.title);
  const [code, setCode] = useState<string>(book.code);
  const [authorId, setAuthorId] = useState<number>(book.authorId);
  const [genreId, setGenreId] = useState<number>(book.genreId);

  const [authors, setAuthors] = useState<Author[]>([]);
  const [genres, setGenres] = useState<Genre[]>([]);

  let newBook: Book = { id: book.id, title, code, authorId, genreId };

  // Fetch authors and genres
  useEffect(() => {
    const fetchAuthors = async () => {
      try {
        const response = await fetch("/api/list/authors");
        const data = await response.json();
        setAuthors(data);
      } catch (error) {
        console.error("Error fetching authors:", error);
        setAuthors([]);
      }
    };

    const fetchGenres = async () => {
      try {
        const response = await fetch("/api/list/genres");
        const data = await response.json();
        setGenres(data);
      } catch (error) {
        console.error("Error fetching genres:", error);
        setGenres([]);
      }
    };

    fetchAuthors();
    fetchGenres();
  }, []);

  const saveBook = async (book?: Book) => {
    if (!book) {
      console.error("No book to save");
      return;
    }
    try {
      const response = await fetch("/api/edit/book", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(newBook),
      });
      if (response.ok) {
        // Reload page to see the updated book
        window.location.reload();
      }
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
    } catch (error) {
      console.error(error);
    }
  };

  const deleteBook = async (book: Book) => {
    try {
      const response = await fetch("/api/delete/book", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(book.id),
      });
      if (response.ok) {
        // Reload page to see the updated book
        window.location.reload();
      }
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
    } catch (error) {
      console.error(error);
    }
  };

  return (
    // Add the pop-up form to edit the book.
    <div className="fixed top-0 left-0 w-full h-full flex items-center justify-center bg-black bg-opacity-50">
      <div
        className="bg-white p-6 rounded shadow-md"
        onClick={(e) => e.stopPropagation()} // Do not trigger blank click event in this div.
      >
        <h2 className="text-2xl font-semibold">{book.title}</h2>
        <form className="mt-4">
          <div className="mb-4">
            <label
              className="block text-gray-700 text-sm font-bold mb-2"
              htmlFor="title"
            >
              Title
            </label>
            <input
              className="shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight"
              id="title"
              type="text"
              onChange={(e) => setTitle(e.target.value)}
              defaultValue={book.title}
            />
          </div>
          <div>
            <label
              className="block text-gray-700 text-sm font-bold mb-2"
              htmlFor="code"
            >
              ISBN-code
            </label>
            <input
              className="shadow border rounded w-full py-2 px-3 mb-2 text-gray-700 leading-tight"
              id="code"
              type="text"
              onChange={(e) => setCode(e.target.value)}
              defaultValue={book.code}
            />
          </div>
          <div>
            <select
              onChange={(e) => {
                setAuthorId(Number(e.target.value));
              }}
              value={authorId}
              className="shadow border rounded w-full py-2 px-3 my-2 leading-tight"
            >
              {authors.map((author: Author) => (
                <option key={author.id} value={author.id}>
                  {author.firstName} {author.lastName}
                </option>
              ))}
            </select>
          </div>
          <div>
            <select
              onChange={(e) => {
                setGenreId(Number(e.target.value));
              }}
              value={genreId}
              className="shadow border rounded w-full py-2 px-3 my-4 leading-tight"
            >
              {genres.map((genre: Genre) => (
                <option key={genre.id} value={genre.id}>
                  {genre.name}
                </option>
              ))}
            </select>
          </div>
          <div className="flex justify-between">
            <button
              type="button"
              className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
              onClick={() => {
                newBook = { id: book.id, title, code, authorId, genreId };
                saveBook(newBook);
              }}
            >
              Save
            </button>
            <button
              type="button"
              className="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded"
              onClick={() => {
                deleteBook(book);
              }}
            >
              Delete
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default BookPopUp;
