// opdracht2/src/components/details/book.vue
<template>
    <ion-content class="ion-padding">
        <ion-item v-for=" (field, index) in fields" :key="index">
            <ion-label position="stacked">{{ field.label }}</ion-label>
            <!--Title and ISBN textbox-->
            <ion-input v-if="field.model !== 'authorId' && field.model !== 'genreId'"
                v-model="selectedBook[field.model]"></ion-input>
            <!--Author and genre picker-->
            <ion-picker v-if="field.model === 'authorId' || field.model === 'genreId'"
                :columns="field.model === 'authorId' ? authors : genres" @ionChange="pickerChange">
                <ion-picker-column v-if="field.model === 'authorId'" :value="selectedBook.authorId" id="author">
                    <ion-picker-column-option v-for="author in authors" :value="author.id">
                        {{ author.firstName }} {{ author.lastName }}
                    </ion-picker-column-option>
                </ion-picker-column>
                <ion-picker-column v-if="field.model === 'genreId'" :value="selectedBook.genreId" id="genre">
                    <ion-picker-column-option v-for="genre in genres" :value="genre.id">
                        {{ genre.name }}
                    </ion-picker-column-option>
                </ion-picker-column>
            </ion-picker>
        </ion-item>
        <ion-button @click="saveBook">Save</ion-button>
        <ion-button @click="closeModal">Close</ion-button>
    </ion-content>
</template>

<script setup lang="ts">
import { ref, defineProps, watch, defineEmits, onMounted } from "vue";
import { IonButton, IonInput, IonContent, IonLabel, IonItem, IonPicker, IonPickerColumn, IonPickerColumnOption } from "@ionic/vue";
import axios from "axios";

// Define interfaces
interface Book {
    id: number;
    title: string;
    code: string;
    authorId: number;
    genreId: number;
}
interface Author {
    id: number;
    firstName: string;
    lastName: string;
    birthYear: number;
    popup?: boolean;
}
interface Genre {
    id: number;
    name: string;
    popup?: boolean;
}

const authors = ref<Author[]>([]);
const genres = ref<Genre[]>([]);

const fetchAuthors = async () => {
    try {
        const response = await axios.get(
            "https://wm.ziasserver.com/api/list/authors"
        );
        authors.value = response.data as Author[];
    } catch (error) {
        console.error("Error fetching authors:", error);
    }
};
const fetchGenres = async () => {
    try {
        const response = await axios.get(
            "https://wm.ziasserver.com/api/list/genres"
        );
        genres.value = response.data as Genre[];
    } catch (error) {
        console.error("Error fetching genres:", error);
    }
};

// Fetch authors and genres on component mount
onMounted(() => {
    fetchAuthors();
    fetchGenres();
});

const pickerChange = (e: CustomEvent) => {
    // Get selected value and column and update selectedBook
    const value = e.detail.value;
    const column = (e.target as HTMLElement).id;

    if (column === 'author') {
        selectedBook.value.authorId = value;
    } else if (column === 'genre') {
        selectedBook.value.genreId = value;
    }
};

// Define props
const props = defineProps<{
    book: Book;
}>();

// Define emits
const emit = defineEmits<{
    (e: 'close'): void;
}>();

// Initialize selectedBook
const selectedBook = ref<Book>({
    id: 0,
    title: '',
    code: '',
    authorId: 0,
    genreId: 0
});

// Define fields for the form
const fields: { label: string, model: keyof Book }[] = [
    { label: 'Title', model: 'title' },
    { label: 'ISBN', model: 'code' },
    { label: 'Author ID', model: 'authorId' },
    { label: 'Genre ID', model: 'genreId' }
];

// Save book function
const saveBook = async () => {
    if (selectedBook.value.id === 0) {
        // Add new book
        await axios.post("https://wm.ziasserver.com/api/create/book", {
            title: selectedBook.value.title,
            code: selectedBook.value.code,
            author: selectedBook.value.authorId,
            genre: selectedBook.value.genreId
        },
            { headers: { 'Content-Type': 'application/json' } }
        );
    } else {
        // Edit existing book
        await axios.post("https://wm.ziasserver.com/api/edit/book", {
            id: selectedBook.value.id,
            title: selectedBook.value.title,
            code: selectedBook.value.code,
            authorId: selectedBook.value.authorId,
            genreId: selectedBook.value.genreId
        },
            { headers: { 'Content-Type': 'application/json' } }
        );
    }
    emit('close'); // Emit close event to parent component
};

// Close modal function
const closeModal = () => {
    emit('close'); // Emit close event to parent component
};

// Watch for props update to reflect in selectedBook
watch(() => props.book, (newBook) => {
    selectedBook.value = { ...newBook };
}, { immediate: true });
</script>

// opdracht1/app/components/add/book.tsx
import React, { useEffect, useState } from "react";

interface Author {
  id: number;
  firstName: string;
  lastName: number;
  birthYear: number;
}

interface Genre {
  id: number;
  name: string;
}

const AddBook: React.FC = () => {
  const [isFormVisible, setIsFormVisible] = useState(false);
  const [authors, setAuthors] = useState<Author[]>([]);
  const [genres, setGenres] = useState<Genre[]>([]);

  useEffect(() => {
    const fetchAuthors = async () => {
      try {
        const response = await fetch("/api/list/authors");
        const data = await response.json();
        setAuthors(data);
      } catch (error) {
        console.error("Error fetching authors:", error);
        setAuthors([]);
      }
    };

    const fetchGenres = async () => {
      try {
        const response = await fetch("/api/list/genres");
        const data = await response.json();
        setGenres(data);
      } catch (error) {
        console.error("Error fetching genres:", error);
        setGenres([]);
      }
    };

    fetchAuthors();
    fetchGenres();
  }, []);

  const toggleFormVisibility = () => {
    setIsFormVisible(!isFormVisible);
  };

  let title = "";
  let code = "";
  let author = "";
  let genre = "";

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const newBook = {
      title,
      code,
      author,
      genre,
    };
    try {
      const response = await fetch("/api/create/book", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(newBook),
      });
      // Reload the page to see the new book
      if (response.ok) {
        window.location.reload();
      }
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
    } catch (error) {
      console.error(error);
    }
  };

  const BookForm: React.FC = () => (
    <form
      onSubmit={handleSubmit}
      className="fixed top-0 left-0 w-full h-full flex items-center justify-center bg-black bg-opacity-50"
      onClick={toggleFormVisibility}
      id="bookForm"
    >
      <div
        className="bg-white p-6 rounded shadow-md"
        onClick={(e) => e.stopPropagation()} // Prevent the form from closing when clicked inside
      >
        <div>
          <input
            type="text"
            id="title"
            placeholder="Enter book title"
            onChange={(e) => {
              title = e.target.value;
            }}
            required
            className="mb-2 p-2 border border-gray-300 rounded"
          />
        </div>
        <div>
          <input
            type="text"
            id="code"
            placeholder="Enter book code"
            onChange={(e) => {
              code = e.target.value;
            }}
            required
            className="mb-2 p-2 border border-gray-300 rounded"
          />
        </div>
        <div>
          <select
            id="author"
            onChange={(e) => {
              author = e.target.value;
            }}
            required
            className="mb-2 p-2 border border-gray-300 rounded w-full"
          >
            <option value="">Select an author</option>
            {authors.map((author: Author) => (
              <option key={author.id} value={author.id}>
                {author.firstName} {author.lastName}
              </option>
            ))}
          </select>
        </div>
        <div>
          <select
            id="genre"
            onChange={(e) => {
              genre = e.target.value;
            }}
            required
            className="mb-2 p-2 border border-gray-300 rounded w-full"
          >
            <option value="">Select a genre</option>
            {genres.map((genre: Genre) => (
              <option key={genre.id} value={genre.id}>
                {genre.name}
              </option>
            ))}
          </select>
        </div>
        <div className="flex justify-center">
          <button type="submit" className="bg-slate-900 text-white p-2 rounded">
            Add Book
          </button>
        </div>
      </div>
    </form>
  );

  return (
    <div>
      <button
        onClick={toggleFormVisibility}
        className="bg-slate-600 p-3 w-full rounded text-slate-100 hover:bg-slate-800"
      >
        {isFormVisible ? "Hide" : "Add"} Book
      </button>
      {isFormVisible && <BookForm />}
    </div>
  );
};

export default AddBook;
